num_entities: 1316471
num_relations: 6097
hidden_dim: 256
question_encoder_name: sentence-transformers/all-MiniLM-L6-v2
freeze_question_encoder: true
graph_encoder_type: hybrid
num_graph_layers: 1
num_diffusion_layers: 1
num_heads: 8
num_diffusion_steps: 25
max_path_length: 100
dropout: 0.1
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 1000
max_steps: 100000
use_multipath_training: true
path_generator_type: diffusion
flow_integration_steps: 32
flow_ce_weight: 0.1
use_entity_embeddings: false
predict_entities: false
