num_entities: 50000
num_relations: 5000
hidden_dim: 128
question_encoder_name: sentence-transformers/all-MiniLM-L6-v2
freeze_question_encoder: false
graph_encoder_type: hybrid
num_graph_layers: 1
num_diffusion_layers: 1
num_heads: 8
num_diffusion_steps: 50
max_path_length: 20
dropout: 0.1
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 1000
max_steps: 100000
