num_entities: 1316471
num_relations: 6097
hidden_dim: 256
question_encoder_name: sentence-transformers/all-MiniLM-L6-v2
freeze_question_encoder: false
num_layers: 6
num_heads: 8
max_path_length: 25
dropout: 0.1
learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 1000
max_steps: 50000000
use_multipath_training: true
decoding_strategy: beam_search
beam_width: 5
top_p: 0.9
top_k: 50
temperature: 1.0
length_penalty: 0.6
use_contrastive_search: false
contrastive_penalty_alpha: 0.6
contrastive_top_k: 4
